#!/bin/sh

#./configure --disable-lastlog --disable-utmp --disable-utmpx --disable-wtmp \
#	--disable-wtmpx --disable-loginfunc --disable-pututline \
#	--disable-pututxline --disable-shadow --disable-syslog \
#	--disable-openpty

./configure --disable-utmp --disable-utmpx --disable-wtmp --disable-wtmpx --disable-shadow --disable-syslog --disable-lastlog
