#!/bin/sh

./configure --disable-pty --disable-cryptlib \
	--disable-utmp --disable-utmpx --disable-wtmp \
	--disable-wtmpx --disable-shadow --disable-syslog \
	--disable-lastlog --disable-loginfunc --disable-openpty
