#!/bin/sh

if [ -z "$ANDK" ]; then
	echo "ANDK does not point at android ndk home"
	exit 1
fi

VER=android-21
ARCH=arm
CROSS_COMPILE=arm-linux-androideabi-
LDFLAGS="--sysroot=$ANDK/platforms/$VER/arch-$ARCH"
LDFLAGS=$LDFLAGS" -L$ANDK/platforms/$VER/arch-$ARCH/usr/lib"
CFLAGS="-I$ANDK/platforms/$VER/arch-$ARCH/usr/include"
CFLAGS=$CFLAGS" -DANDROID"

export ARCH CROSS_COMPILE CFLAGS LDFLAGS

n=$(grep "processor" /proc/cpuinfo | wc -l)
if [ -z "$n" ]; then
	n=1
fi

echo "COMPILE: $CROSS_COMPILE" | grep --color "$CROSS_COMPILE"
echo "THREADS: $n" | grep --color [0-9]

echo "Distclean? [y/n]" | grep --color -E "\/n"
read str
case $str in
y|yes) make V=1 distclean && make V=1;;
*) make V=1 clean && make -j$n V=1 STATIC=1 MULTI=1 \
	PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp";;
esac
